# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_wd(object):
    def setupUi(self, main_wd):
        main_wd.setObjectName("main_wd")
        main_wd.resize(300, 128)
        main_wd.setMinimumSize(QtCore.QSize(300, 128))
        main_wd.setMaximumSize(QtCore.QSize(300, 128))
        self.pushButton = QtWidgets.QPushButton(main_wd)
        self.pushButton.setGeometry(QtCore.QRect(220, 20, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(main_wd)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 44, 50))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(main_wd)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 281, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(main_wd)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 151, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(main_wd)
        self.label_6.setGeometry(QtCore.QRect(10, 90, 101, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(main_wd)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 110, 221, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(main_wd)
        self.label_7.setGeometry(QtCore.QRect(190, 90, 111, 20))
        self.label_7.setObjectName("label_7")
        self.widget = QtWidgets.QWidget(main_wd)
        self.widget.setGeometry(QtCore.QRect(60, 10, 151, 51))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)

        self.retranslateUi(main_wd)
        QtCore.QMetaObject.connectSlotsByName(main_wd)

    def retranslateUi(self, main_wd):
        _translate = QtCore.QCoreApplication.translate
        main_wd.setWindowTitle(_translate("main_wd", "塔科夫助手 作者：这风吹得我真冷"))
        self.pushButton.setText(_translate("main_wd", "开始捡垃圾"))
        self.label.setText(_translate("main_wd", "APPID:"))
        self.label_3.setText(_translate("main_wd", "APPKEY:"))
        self.label_2.setText(_translate("main_wd", "APPSK:"))
        self.label_4.setText(_translate("main_wd", "使用方法：把自己的key输入到框框里，然后点击开始，然后就可以用了"))
        self.label_5.setText(_translate("main_wd", "初代版本，有bug，还请见谅"))
        self.label_6.setText(_translate("main_wd", "欢迎关注B站账号："))
        self.lineEdit_4.setText(_translate("main_wd", "https://space.bilibili.com/36333545"))
        self.lineEdit_4.setPlaceholderText(_translate("main_wd", "推广一下自己你也删了干嘛"))
        self.label_7.setText(_translate("main_wd", "后续有时间了再更新"))
